name: ATH Detection Backup (Offset)
on:
  schedule:
    # Run 30 seconds after main workflow (offset to increase frequency)
    # This creates effectively 30-second intervals when combined with main workflow
    - cron: '* * * * *'  # Every minute (but delayed by 30 seconds in the script)
  workflow_dispatch: # Allow manual triggers for testing

jobs:
  ath-detection-backup:
    name: ATH Detection Backup
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
      - name: Wait 30 seconds (offset)
        run: sleep 30
        
      - name: ATH Detection Backup
        run: |
          echo "🔍 Starting backup ATH detection for CoinSpree..."
          echo "⏰ Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          echo "🔄 This is the backup/offset workflow for increased frequency"
          
          # Make authenticated request to ATH detection endpoint
          RESPONSE=$(curl -s -w "HTTP_STATUS:%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" \
            -H "User-Agent: CoinSpree-GitHub-Actions-Backup/1.0" \
            --max-time 25 \
            "${{ secrets.VERCEL_DEPLOYMENT_URL }}/api/cron/ath-detection")
          
          # Extract HTTP status and body
          HTTP_STATUS=$(echo "$RESPONSE" | grep -o "HTTP_STATUS:[0-9]*" | cut -d: -f2)
          BODY=$(echo "$RESPONSE" | sed 's/HTTP_STATUS:[0-9]*$//')
          
          echo "📊 Backup Response Status: $HTTP_STATUS"
          
          # Check if request was successful
          if [ "$HTTP_STATUS" -eq 200 ]; then
            # Parse response
            ATH_COUNT=$(echo "$BODY" | grep -o '"athCount":[0-9]*' | cut -d: -f2 2>/dev/null || echo "0")
            DURATION=$(echo "$BODY" | grep -o '"duration":[0-9]*' | cut -d: -f2 2>/dev/null || echo "0")
            
            echo "✅ Backup ATH detection completed successfully"
            echo "🚀 ATH Count: $ATH_COUNT"
            echo "⏱️ Processing time: ${DURATION}ms"
            
            # Success summary
            if [ "$ATH_COUNT" -gt 0 ]; then
              echo "🎉 BACKUP: $ATH_COUNT new All-Time Highs detected!"
            else
              echo "📈 BACKUP: No new ATHs detected this cycle"
            fi
            
            # Log workflow success
            echo "::notice title=Backup ATH Detection Success::Processed $ATH_COUNT ATHs in ${DURATION}ms"
            
          else
            echo "❌ Backup workflow failed with status: $HTTP_STATUS"
            echo "🔍 Response body: $BODY"
            # Don't fail the backup workflow - it's supplementary
            echo "::warning title=Backup Failed::Backup ATH detection returned HTTP $HTTP_STATUS"
          fi
        env:
          VERCEL_DEPLOYMENT_URL: ${{ secrets.VERCEL_DEPLOYMENT_URL }}
          CRON_SECRET_KEY: ${{ secrets.CRON_SECRET_KEY }}